---

plugin: openstack.cloud.openstack

# for each tag defined in the VMs we add it to the right group
# e.g. if VM has tags "login_node" and "slurm_sumbmit" it will
# belong to those two groups in the ansible inventory
keyed_groups:
  - key: openstack.tags | default([])
    prefix: ""
    separator: ""

all_projects: false
inventory_hostname: name
expand_hostvars: true
fail_on_errors: true
strict: true
