---

- name: Configure NTP time
  ansible.builtin.import_role:
    name: geerlingguy.ntp

- name: Add EPEL yum repo | RedHat
  ansible.builtin.package:
    name: epel-release
    state: installed
  when: ansible_os_family == 'RedHat'

- name: Disable SElinux in RedHat systems
  ansible.builtin.import_role:
    name: pescobar.selinux_disable
  vars:
    selinux_disable_reboot: true
  when: ansible_os_family == 'RedHat'

- name: Install some basic packages defined in variable 'local_packages_to_install'
  ansible.builtin.package:
    name: "{{ local_packages_to_install }}"

- name: Upgrade all the packages (if configured)
  ansible.builtin.yum:
    name: '*'
    state: latest
  tags:
    - skip_ansible_lint
  when:
    - local_upgrade_all_packages
    - ansible_os_family == 'RedHat'
