
---

# yaml inventory based on https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml
#
# In this inventory we only define "behavioral inventory parameters" or local variables "local_apply_role_XXX"
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters
#
# ROLE VARIABLES SHOULD BE DEFINED IN INVENTORY/GROUP_VARS/ OR INVENTORY/HOST_VARS/
#
# Useful debug commands:
#
# print groups for host login1:
# $> ansible -i inventory/hosts.yml -m debug -a var="hostvars['login1']['group_names']" login1
#login1 | SUCCESS => {
#    "hostvars['login1']['group_names']": [
#        "compute_cluster",
#        "login_nodes"
#    ]
#}

# print which roles will apply to host login1
# $> ansible -i inventory/hosts.yml -m debug -a var="hostvars['login1']" login1 | grep apply_role
# "local_apply_role_x2go": true,

# all:
#   vars:
#     ansible_ssh_extra_args: '-F {{ playbook_dir }}/inventory/ssh.cfg'

# vagrant:
#   hosts:
#     default:
#       ansible_host: 192.168.111.222
#       ansible_user: vagrant
#       local_apply_role_disable_selinux: True


# login_nodes:
#   hosts:
#     login1:
#       ansible_host: 191.168.100.32
#       ansible_user: root
#       ansible_port: 2222
#       ansible_ssh_private_key_file: ~/.ssh/id_rsa
#     login2:
#   vars:
#     local_apply_role_iptables: True
#     local_apply_role_fail2ban: True


# compute_nodes:
#   hosts:
#     compute1:
#     compute2:
#   vars:
#     local_apply_role_gpfs: True


# compute_cluster:
#   children:
#     login_nodes:
#     compute_nodes:


# webservers:
#   hosts:
#     web01:
#     web02:
#   vars:
#     local_apply_role_dehydrated: True
#     local_apply_role_apache: True

