---

name: Lint tests # feel free to pick your own name
on: [push, pull_request]

jobs:

  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'config/ ansible/'
          yamllint_strict: false
          yamllint_comment: false
        # env:
        #   GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  ansible-lint:
    name: 'ansible-lint'
    runs-on: ubuntu-latest
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible-community/ansible-lint-action@main
        # optional:
        # with:
        #   path: "playbooks/"  # <-- only one value is allowed
        path: "ansible/"  # <-- only one value is allowed
