---

name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  tofu-lint:
    name: OpenTofu format check and validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: tofu fmt
        working-directory: opentofu
        run: tofu fmt -check -recursive

      - name: tofu init
        working-directory: opentofu
        run: tofu init -backend=false

      - name: tofu validate
        working-directory: opentofu
        run: tofu validate

  ansible-lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ansible
        run: pip install -r requirements.txt ansible-lint

      - name: Run ansible-lint
        working-directory: ansible
        run: ansible-lint playbooks/
